module "codecov" {
  source = "../terraform-k8s-codecov"
  config_context = "kubernetes-admin@kubernetes"
  web_replicas = "2"
  worker_replicas = "2"
  minio_replicas = "4"
  codecov_yml = "${var.codecov_yml}"
  nfs_pv_host = "${var.nfs_pv_host}"
  nfs_pv_path = "${var.nfs_pv_path}"
  nfs_pv_size = "${var.nfs_pv_size}"
  minio_access_key = "${var.minio_access_key}"
  minio_secret_key = "${var.minio_secret_key}"
  ingress_host = "phil-ccmigrate-terraform.ngrok.io"
  enable_https = "0"
  tls_key = "${path.module}/creds/key.pem"
  tls_cert = "${path.module}/creds/cert.pem"
}
