# vim: set ft=ruby:

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "10.253.0.15"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 8192
  end

  config.vm.provision "shell", path: "scripts/install_docker.sh"
  config.vm.provision "shell", path: "scripts/install_kubernetes.sh"
  config.vm.provision "shell", path: "scripts/install_tools.sh"

  config.vm.synced_folder ".", "/vagrant", 
    type: "nfs",
    nfs_udp: false,
    nfs_version: 4,
    create: true

  config.vm.synced_folder "/home/phil/codecov/docker-compose", "/docker-compose", 
    type: "nfs",
    nfs_udp: false,
    nfs_version: 4,
    create: true
end
